# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  build:
    desc: Build frontend + Go binaries (debug and release in one pass)
    deps: [rpc:generate]
    cmd: pnpm exec vite build

  start:
    desc: Run the release binary
    cmds:
      - pnpm exec kill-port 3000 3080
      - ./build/release/{{.APP_NAME}} --env-file=.env.local serve {{.CLI_ARGS}}

  release:
    desc: Build release binaries via goreleaser
    deps: [rpc:generate]
    cmd: goreleaser build --clean --auto-snapshot

  publish:
    desc: Publish a release via goreleaser
    deps: [rpc:generate]
    cmd: goreleaser release --clean --auto-snapshot
