# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

# @reference: https://stackoverflow.com/questions/59813998/github-actions-splitting-workflow-file
# @reference: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: setup-sdk
description: Prepare development environment

inputs:
  nodeVersion:
    description: "Nodejs version"
    required: false
    default: "24"
  goVersion:
    description: "Golang version"
    required: false
    default: ">=1.27.0"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v7
      with:
        node-version: ${{ inputs.nodeVersion }}

    - uses: pnpm/action-setup@v6
      with:
        run_install: false
        cache: true

    - name: Setup Golang toolchain
      uses: actions/setup-go@v7
      with:
        token: ${{ github.token }}
        go-version: ${{ inputs.goVersion }}
        cache-dependency-path: "go.sum"
        cache: true
