# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

name: tango

x-common: &common
  networks: ["intranet"]
  extra_hosts: ["host.docker.internal:host-gateway"]
  restart: unless-stopped
  security_opt: ['no-new-privileges:true']
  shm_size: 128m # set shared memory limit
  mem_limit: 256m # set memory limit
  cpus: 1.0 # set CPUs limit

include:
  - ./compose-dev.yaml
  - ./compose-mock.yaml
  - ./compose-sre.yaml

# services:
#   tango:
#     <<: *common
#     build:
#       context: .
#       dockerfile: ./deploy/Dockerfile
#       args:
#         DISTROLESS_TAG: ${DISTROLESS_TAG:-nonroot}
#         NODE_VERSION: ${NODE_VERSION:-24.21}
#         GO_VERSION: ${GO_VERSION:-1.27.1}
#     # platform: linux/amd64
#     hostname: tango
#     expose: ["3000"]
#     volumes: ["./storage:/srv/storage:rw"]
#     env_file: "./.env.local"
#     environment:
#       DATABASE_URL: postgresql://postgres:securedb@pgsql:5432/postgres?sslmode=disable
#       STORAGE_S3_ENDPOINT_URL: http://silo:9100
#       MAILER_SMTP_HOST: mailpit
#     healthcheck:
#       test: ["CMD", "/srv/tango", "health", "--short"]
#       interval: 3s
#       timeout: 5s
#       retries: 3
#     depends_on:
#       pgsql: { condition: service_healthy }
#       silo: { condition: service_healthy }

networks:
  intranet:
    driver: bridge
    enable_ipv6: false
