# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Test

on:
  push:
    branches: ["**"]
    tags-ignore: ["*"]
  pull_request:

permissions: read-all

env:
  CI: true
  LEFTHOOK: 0
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
  CGO_ENABLED: 0

jobs:
  test:
    name: Test
    strategy:
      matrix:
        # @ref: https://github.com/actions/runner-images
        os: [ubuntu-24.04, macos-15]
        go-version: ["1.27.x"]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run actions/setup-sdk@local
        uses: ./.github/setup-sdk
        with:
          goVersion: ${{ matrix.go-version }}

      - if: ${{ steps.pnpm-cache.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: |
          pnpm install --ignore-scripts --frozen-lockfile
          go mod download && go mod tidy
          go install github.com/go-task/task/v3/cmd/task@latest
          go install gotest.tools/gotestsum@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          # templ generate

      - name: Setup golangci-lint toolchain
        uses: golangci/golangci-lint-action@v9
        with:
          github-token: ${{ github.token }}
          install-mode: binary
          version: v2.11

      - name: Check code quality
        run: task check lint
        env:
          GOEXPERIMENT: jsonv2
          NODE_ENV: production

      - name: Run unit tests (frontend)
        run: task test:ui
        env:
          NODE_ENV: production

      - name: Run unit tests (backend)
        run: task test:go
        env:
          GOEXPERIMENT: jsonv2
          NODE_ENV: production

      - name: Build application binaries
        run: task build
        env:
          GOEXPERIMENT: jsonv2
          NODE_ENV: production
